#项目构建环境Node
language: node_js

# Node版本 10
node_js:
  - "10"

# 依赖安装
install:
  - npm install

# 代码打包
script:
  - npm run build

# 发布到gh-pages
deploy:
  provider: pages
  email: 826526881@qq.com
  name: kitorv
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
